apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contacts_user
  namespace: contacts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: contacts_user
