apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 192.168.2.0/24
      avoid-buggy-ips: true
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 64512
      my-asn: 64512
