apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts
      tier: backend
  template:
    metadata:
      labels:
        app: contacts
        tier: backend
    spec:
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:5.6
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
