apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contacts
      tier: frontend
  template:
    metadata:
      labels:
        app: contacts
        tier: frontend
    spec:
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: php-pv-claim
      - name: config
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - name: code
          mountPath: /code
        - name: config
          mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
