apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: frontend
spec:
  selector:
    app: contacts
    tier: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
